version: '3.9'

services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - pg

