version: '3.9'

services:
  pg:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  api:
    build:
      context: .
    ports:
      - 80:5000
    depends_on:
      - pg